### ISSUE TITLE
WGU would like to change the content of the "Help Button Popup"

### ISSUE THREAD

**Issue by ExcelsiorMarc** [DAACS/DAACS-Website#32]
The precise content has yet to be provided. However, they want it to be modified to direct the students to various support mechanisms that better match the WGU enterprise support structures. The goal is to improve Service Request response times at WGU, for DAACS.

Enhancement Recommendation for V2.0: We may consider making this a configurable item, within the context of the Admin functionality.

**Comment by Mavann1988** [comment]
@ExcelsiorMarc This is something we'd have to change in the source code. We'd also have to consider what this means for Excelsior.

**Comment by ExcelsiorMarc** [comment]
Added this to the change request list in Issue #33
