### ISSUE TITLE
WGU Change Requests

### ISSUE THREAD

**Issue by ExcelsiorMarc** [DAACS/DAACS-Website#33]
Hi Alan,

WGU’s next round of students to complete DAACS starts Monday. We currently don’t have Lightside models with sufficient accuracy. In order to buy us some time, they have agreed to have students complete the writing assessment but want to change the directions to indicate that the essay is for their mentor and reflecting. As such, we would like to make a few, hopefully minor, tweaks to the UI:

•	Hide the circles on the dashboard page for writing only?
•	Change the message on the completion page.
•	Hide the “Check for results” button on the results page.
•	It would also be nice, if easy, to just show the student’s essay on the ungraded page under the message.

Thanks,
Jason

**Comment by ExcelsiorMarc** [comment]
1.	Hide the “Check for results” button on the results page.
2.	Show the student’s essay on the ungraded page under the message.
3.	Change the message on the completion page: Chelsea is crafting some language.
4.	Hide the circles on the dashboard page for writing only?
5.	Change the content of the "Help" popup (for WGU only, this can wait until next week?)

**Comment by Mavann1988** [comment]
All changes are completed and pushed to prod.
